name: "build-test"
on:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get version
      id: version
      run: |
        export ACTION_VERSION=`awk -F'"' '/version/ { print $4 }' package.json`
        echo "::set-output name=ACTION_VERSION::$ACTION_VERSION"
    - uses: ./
      with:
        webhook-url: ${{ secrets.TEST_WEBHOOK_URL }}
        title: New Action update
        message: "version: ${{ steps.version.outputs.ACTION_VERSION }}"
        url: https://github.com/insprac/discord-notification-action
        color: "#75c22d"
