name: "build-test"
on:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        webhook-url: ${{ secrets.TEST_WEBHOOK_URL }}
        title: Test Notification
        message: Successful test.
        url: https://github.com/insprac/discord-notification-action
        color: "#75c22d"
